;;; -*- lexical-binding: t -*-
;;;
;;; This file is automatically generated. DO NOT EDIT.
;;;
;;; To regenerate, run:
;;;   bazel run infra/tools/ghsync:main -- schema --output <path-to-this-file>

'(
  (sync_metadata
   [
    (user text :not-null)
    (repository text :not-null)
    (endpoint text :not-null)
    (last_sync_timestamp text)
    (etag text)
   ]
   (:primary-key user repository endpoint)
  )
  (repositories
   [
    (id integer :primary-key)
    (full_name text :not-null :unique)
    (fork integer :not-null)
    (created_at text)
    (pushed_at text)
    (updated_at text)
    (visibility text)
    (forks integer)
    (default_branch text)
   ]
  )
  (issues
   [
    (id integer :primary-key)
    (number integer :not-null)
    (title text)
    (type text :not-null)
    (state text :not-null)
    (draft integer :not-null :default 0)
    (created_at text :not-null)
    (updated_at text :not-null)
    (closed_at text)
    (merged_at text)
    (repository_id integer :not-null)
   ]
   (:foreign-key (repository_id) (repositories id))
   (:unique repository_id number)
  )
  (labels
   [
    (id integer :primary-key)
    (repository_id integer :not-null)
    (name text :not-null)
    (color text)
    (description text)
   ]
   (:foreign-key (repository_id) (repositories id))
   (:unique repository_id name)
  )
  (issue_labels
   [
    (issue_id integer :not-null)
    (label_id integer :not-null)
   ]
   (:primary-key issue_id label_id)
   (:foreign-key (issue_id) (issues id))
   (:foreign-key (label_id) (labels id))
  )
)
