;;; -*- lexical-binding: t -*-

(require 'cl-lib)
;;;
;;; This file is automatically generated. DO NOT EDIT.
;;;
;;; To regenerate, run:
;;;   bazel run infra/tools/ghsync:main -- model --output <path-to-this-file>
;;;
;;; Not sure about the autogen thing. For now we added a labels list
;;; to neo-issues arguably ghsync could be made smarter and realize
;;; that's needed when there's a many-to-many relation, but for now it
;;; doesn't do anything that smart.
(cl-defstruct neo-sync-metadata
  user                  ;; string
  repository            ;; string
  endpoint              ;; string
  last-sync-timestamp   ;; string or nil
  etag)                 ;; string or nil


(cl-defstruct neo-repository
  id               ;; integer or nil
  full-name        ;; string
  fork             ;; integer
  created-at       ;; string or nil
  pushed-at        ;; string or nil
  updated-at       ;; string or nil
  visibility       ;; string or nil
  forks            ;; integer or nil
  default-branch)  ;; string or nil


(cl-defstruct neo-label
  id               ;; integer
  name             ;; string
  color            ;; string or nil
  description      ;; string or nil
  repository-id)   ;; integer


(cl-defstruct neo-issue
  id              ;; integer or nil
  number          ;; integer
  title           ;; string or nil
  type            ;; string
  labels          ;; list of neo-label
  state           ;; string
  draft           ;; integer
  created-at      ;; string
  updated-at      ;; string
  closed-at       ;; string or nil
  merged-at       ;; string or nil
  repository-id   ;; integer
  stack           ;; neo-stack or nil
  ui-state)       ;; string ("expanded" or "collapsed")

(provide 'github-models)
