;;; -*- lexical-binding: t -*-

(defun neo/screen-geometry ()
  "Return the geometry of the primary monitor as a plist: (:x X :y Y :width W :height H).
Should work on X11 and Wayland."
  (let* ((monitors (display-monitor-attributes-list))
         (primary (car monitors))  ;; Fallback: first monitor
         (geom (assq 'geometry primary)))
    (when geom
      (let ((g (cdr geom)))
        (list :x (nth 0 g)
              :y (nth 1 g)
              :width (nth 2 g)
              :height (nth 3 g))))))

(defun neo/display-dpi (&optional display)
  "Return the approximate DPI of DISPLAY (default: selected frame's display).
Returns a cons cell (dpi-x . dpi-y), or nil if unavailable."
  (let* ((display (or display (frame-parameter nil 'display)))
         (mm-width (display-mm-width display))
         (mm-height (display-mm-height display))
         (px-width (display-pixel-width display))
         (px-height (display-pixel-height display)))
    (when (and mm-width mm-height (> mm-width 0) (> mm-height 0))
      (cons
       (/ (* px-width 25.4) mm-width)   ;; dpi-x = pixels / (mm / 25.4)
       (/ (* px-height 25.4) mm-height)))))

(defun neo/font-height-to-fit-lines (lines &optional font-name)
  "Return the font height needed to fit LINES vertically in the current screen.
Optional FONT-NAME can be used to compute based on a specific font family."
  (interactive "nNumber of lines to fit: ")
  (let* ((geom (neo/screen-geometry))
         (screen-height (plist-get geom :height))
         (window (selected-window))
         (line-height
          (condition-case nil
              (let* ((start-pos (posn-at-point (point-min) window))
                     (end-pos (posn-at-point (save-excursion (goto-char (point-min)) (forward-line 1) (point)) window))
                     (start-px (and start-pos (cdr (posn-x-y start-pos))))
                     (end-px   (and end-pos (cdr (posn-x-y end-pos)))))
                (if (and start-px end-px)
                    (- (cdr end-px) (cdr start-px))
                  (frame-char-height)))
            (error (frame-char-height))))
         (current-font-height (face-attribute 'default :height))
         (font-height (floor (* current-font-height (/ (float screen-height) (* lines line-height))))))
    (when (called-interactively-p 'interactive)
      (message "Calculated font height: %d (for %d lines, %d px line height)" font-height lines line-height))
    font-height))

(defun neo/save-initial-frame-properties ()
  "Save the current frame size, font, and default face background/foreground
to a file that can be loaded from early-init.el."
  (interactive)
  (let* ((frame (selected-frame))
         (font (frame-parameter frame 'font))
         (width (frame-width))
         (height (frame-height))
         (bg (face-background 'default nil t))
         (fg (face-foreground 'default nil t))
         (font-attr (face-attribute 'default :font nil 'default))
         (family (face-attribute 'default :family nil 'default))
         (font-height (face-attribute 'default :height nil 'default))
         (file (neo/config-file-path "initial-frame-properties.el")))
    (make-directory (file-name-directory file) t)
    (with-temp-file file
      (insert ";; Auto-generated by neo/save-initial-frame-properties\n")
      (insert "(setq initial-frame-alist\n")
      (insert (format "      '((width . %d)\n" width))
      (insert (format "        (height . %d)\n" height))
      (insert (format "        (font . %S)\n" font))
      (insert "        (internal-border-width . 0)\n")
      (insert "        (undecorated . nil)))\n\n")
      (insert "(setq default-frame-alist initial-frame-alist)\n\n")
      (insert (format "(set-face-attribute 'default nil :background %S :foreground %S :family %S :height %d)\n"
                      bg fg family font-height)))))

(defun neo--nearest-ratio (ratio)
  "Return the nearest canonical ratio described as (W H NAME)."
  (let* ((candidates
          ;; list of (W H NAME)
          '((1 1 "1:1")
            (4 3 "4:3")
            (5 4 "5:4")
            (16 10 "16:10")
            (3 2 "3:2")
            (16 9 "16:9")
            (21 9 "21:9")
            (24 10 "24:10")
            (32 9 "32:9")))
         (best nil)
         (best-diff 1e9))
    (dolist (c candidates)
      (let* ((w (nth 0 c))
             (h (nth 1 c))
             (r (/ (float w) (float h)))
             (diff (abs (- r ratio))))
        (when (< diff best-diff)
          (setq best-diff diff)
          (setq best c))))
    ;; return list (W H NAME DIFF RATIO)
    (let* ((w (nth 0 best))
           (h (nth 1 best))
           (name (nth 2 best))
           (r (/ (float w) (float h)))
           (diff best-diff))
      (list w h name diff r))))

(defun neo--aspect-family-from-ratio (ratio)
  "Return an aspect-family keyword for numeric RATIO (width/height)."
  (cond
   ((= (round (* ratio 100)) 100) 'square) ;; approx 1:1
   ((> ratio 3.0) 'super-ultrawide)
   ((> ratio 2.0) 'ultrawide)
   ((> ratio 1.8) 'wide)
   ((> ratio 1.4) 'regular)
   (t 'tall)))

(defun neo--resolution-class-from-pixels (total-px width height)
  "Classify by total pixel count TOTAL-PX (and optionally width/height)."
  (cond
   ((>= total-px 33000000) '8k)
   ((>= total-px 20000000) '6k)
   ((>= total-px 14000000) '5k)
   ((>= total-px 8000000)  '4k)   ;; ~8.3MP
   ((>= total-px 3500000)  'qhd)  ;; ~3.5MP
   ((>= total-px 2000000)  'fhd)  ;; ~2MP
   ((>= total-px 800000)   'hd)
   (t 'vga)))

(defun neo--dpi-class (dpi)
  "Return dpi class keyword from DPI average."
  (cond
   ((< dpi 100) 'low-dpi)
   ((< dpi 150) 'standard-dpi)
   ((< dpi 250) 'hidpi)
   (t 'ultra-hidpi)))

(defun neo--ui-pt-for-dpi-class (class)
  (pcase class
    ('low-dpi      11.0)
    ('standard-dpi 12.5)
    ('hidpi        14.0)
    ('ultra-hidpi  16.0)
    (_             12.5)))

(defun neo--code-pt-from-ui-pt (ui-pt)
  (* ui-pt 0.92))

(defun neo--pt->px (pt dpi)
  (* pt (/ dpi 72.0)))

(defun neo--recommended-scale (dpi-class dpi)
  "Return a suggested UI scale factor (float) based on DPI-CLASS and DPI."
  (pcase dpi-class
    ('low-dpi 1.25)
    ('standard-dpi 1.0)
    ('hidpi 1.5)
    ('ultra-hidpi (if (> dpi 300) 2.0 1.75))
    (_ 1.0)))

;;;###autoload
(defun neo/classify-monitor-aux (width height dpi-h dpi-v)
  "Classify a monitor given pixel size WIDTH x HEIGHT and DPI_H / DPI_V.
WIDTH and HEIGHT are pixels (integers). DPI_H and DPI_V are pixels-per-inch
(horizontal and vertical). Returns a plist with classification fields."
  (unless (and (numberp width) (numberp height) (> width 0) (> height 0))
    (error "Width and height must be positive numbers"))
  (let* ((w (float width))
         (h (float height))
         (orientation (if (>= w h) 'landscape 'portrait))
         (ratio (/ w h))
         (ratio-inv (/ h w))
         (ratio-nearest (neo--nearest-ratio ratio))
         (ratio-name (nth 2 ratio-nearest))
         (ratio-diff (nth 3 ratio-nearest))
         (ratio-canon (format "%d:%d" (nth 0 ratio-nearest) (nth 1 ratio-nearest)))
         (aspect-family (neo--aspect-family-from-ratio ratio))
         (total-px (round (* w h)))
         (resolution-class (neo--resolution-class-from-pixels total-px width height))
         (dpi-h (float dpi-h))
         (dpi-v (float dpi-v))
         (dpi-avg (/ (+ dpi-h dpi-v) 2.0))
         (dpi-class (neo--dpi-class dpi-avg))
         (recommended-scale (neo--recommended-scale dpi-class dpi-avg))
         (aspect-string (if (<= ratio-diff 0.03) ; within ~3% -> canonical name
                            ratio-canon
                          (format "%.2f:1" (round (* ratio 100.0))))) ;; fallback
         ;; collect some helpful human strings
         (human (list
                 (cons 'resolution (format "%dx%d" width height))
                 (cons 'total_pixels total-px)
                 (cons 'aspect_ratio (format "%.4f" ratio))
                 (cons 'aspect_nearest ratio-name)
                 (cons 'orientation (symbol-name orientation))
                 (cons 'dpi_avg (format "%.1f" dpi-avg)))))
    ;; Return plist
    (list
     :width width
     :height height
     :total-pixels total-px
     :resolution-class resolution-class
     :orientation orientation
     :aspect-ratio aspect-string
     :aspect-family aspect-family
     :canonical-aspect ratio-canon
     :aspect-nearest-name (nth 2 ratio-nearest)
     :aspect-nearest-diff (round (* 1000 (nth 3 ratio-nearest))) ; thousandth of difference
     :dpi-h dpi-h
     :dpi-v dpi-v
     :dpi-avg dpi-avg
     :dpi-class dpi-class
     :recommended-scale recommended-scale
     :human human)))

(defun neo/classify-monitor-aux (width height dpi-h dpi-v)
  "Return a plist describing the monitor:
 - orientation (portrait/landscape)
 - aspect-ratio category
 - resolution class (HD/WQHD/4K/etc)
 - DPI class
 - plus recommended UI & code font sizes (pt + px)."
  (let* ((w (float width))
         (h (float height))
         (aspect (/ w h))
         ;; orientation
         (orientation (if (> h w) 'portrait 'landscape))

         ;; aspect ratio class
         (aspect-class
          (cond
           ((< aspect 1.4) 'regular)      ;; 4:3, 5:4
           ((< aspect 2.1) 'widescreen)   ;; 16:10, 16:9
           ((< aspect 3.1) 'ultrawide)    ;; 21:9
           (t               'superultrawide))) ;; 32:9, 48:9

         ;; resolution class
         (res-class
          (cond
           ((<= h 900) 'hd)
           ((<= h 1440) 'wqhd)
           ((<= h 2160) '4k)
           ((<= h 2880) '5k)
           ((<= h 4320) '8k)
           (t 'insane)))
	 (ratio (/ w h))
         (ratio-inv (/ h w))
         (ratio-nearest (neo--nearest-ratio ratio))
         (ratio-name (nth 2 ratio-nearest))
         (ratio-diff (nth 3 ratio-nearest))
         (ratio-canon (format "%d:%d" (nth 0 ratio-nearest) (nth 1 ratio-nearest)))
         (aspect-family (neo--aspect-family-from-ratio ratio))
	 (aspect-string (if (<= ratio-diff 0.03) ; within ~3% -> canonical name
                            ratio-canon
                          (format "%.2f:1" (round (* ratio 100.0))))) ;; fallback
         ;; DPI handling
         (dpi-h (float dpi-h))
         (dpi-v (float dpi-v))
         (dpi-avg (/ (+ dpi-h dpi-v) 2.0))
         (dpi-class (neo--dpi-class dpi-avg))

         ;; font recommendations
	 (dpi-avg (/ (+ dpi-h dpi-v) 2.0))
	 (dpi-class (neo--dpi-class dpi-avg))
         (recommended-scale (neo--recommended-scale dpi-class dpi-avg))
         (ui-pt (neo--ui-pt-for-dpi-class dpi-class))
         (code-pt (neo--code-pt-from-ui-pt ui-pt))
         (ui-px (round (neo--pt->px ui-pt dpi-avg)))
         (code-px (round (neo--pt->px code-pt dpi-avg))))

    (list
     ;; basic geometry
     :width width
     :height height
     :orientation orientation
     :aspect aspect
     :aspect-class aspect-class
     :resolution-class res-class
     :aspect-ratio aspect-string
     :aspect-family aspect-family
     :canonical-aspect ratio-canon
     :aspect-nearest-name (nth 2 ratio-nearest)
     :aspect-nearest-diff (round (* 1000 (nth 3 ratio-nearest))) ; thousandth of difference
     :recommended-fullscreen (neo/frame-fullscreen-or-window width height)
     ;; DPI
     :dpi-h dpi-h
     :dpi-v dpi-v
     :dpi dpi-avg
     :dpi-class dpi-class

     ;; recommended fonts
     :recommended-scale recommended-scale
     :ui-pt ui-pt
     :ui-px ui-px
     :code-pt code-pt
     :code-px code-px)))

(defun neo/classify-monitor ()
  (let* ((screen-geometry (neo/screen-geometry))
	 (width (plist-get screen-geometry :width))
	 (height (plist-get screen-geometry :height))
	 (screen-resolution (neo/display-dpi))
	 (x-dpi (car screen-resolution))
	 (y-dpi (cdr screen-resolution)))
    (message "%sx%s (%s %s)" width height x-dpi y-dpi)
    (neo/classify-monitor-aux width height x-dpi y-dpi)))


;; (defun neo/frame-fullscreen-or-window ()
;;   "Decide whether to make the frame full-screen or windowed.
;; Example logic: use full-screen on large monitors, normal window on smaller ones."
;;   (let* ((attrs (frame-monitor-attributes))
;;          (width (alist-get 'workarea attrs :width))
;;          (height (alist-get 'workarea attrs :height))
;;          ;; Thresholds for "large" display (you can adjust)
;;          (large-width 1920)
;;          (large-height 1080))
;;     (if (and (>= width large-width) (>= height large-height))
;;         'fullboth      ;; full-screen
;;       nil)))  

(defun neo/frame-fullscreen-or-window (width height)
  "Decide whether to make the frame full-screen or windowed.
Use full-screen on large monitors, normal window on smaller ones."
  (let* ((large-width 1920)
         (large-height 1080))
    (if (and width height
             (>= width large-width)
             (>= height large-height))
        'fullboth			; TODO make it customizable there's maximized and fullscreen as well
      nil)))

;; (set-frame-parameter nil 'fullscreen 'fullboth)

;; ;; Apply to initial frame
;; (add-to-list 'initial-frame-alist
;;              `(fullscreen . ,(neo/frame-fullscreen-or-window)))

(provide 'neo-ui-frame)
